### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by maxcell**
After several arduous hours, we got that CI up and running. We should be sure to add the badge later but for now 👍

### CODE REVIEW

**Comment by stevenpetryk** [comment]
The badge is what makes it real, though.

**Comment by stevenpetryk** [comment]
Any reason this includes the changes from #1? Could you rebase against develop and exclude those commits?

**Comment by maxcell** [comment]
True, I wasn't sure if the badge worked without a given branch. Let me see if I can get that on there.

**Comment by maxcell** [comment]
@stevenpetryk I discussed this with Greg already waiting for him to fix something on #1 and we will be rebasing :)

**Comment by stevenpetryk** [comment]
Ah swag, just making sure!

**Review by GregKWhite — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
