### PR TITLE
Add ability to un/subscribe to other users

### PR DESCRIPTION
**Pull request by GregKWhite**
I also cleaned up some user factory nonsense

### CODE REVIEW

**Review by stevenpetryk — APPROVED** [review]

**Comment by stevenpetryk** [comment]
MERGE ASAP WE GOTTA SHIP

**Comment by stevenpetryk** [comment]
MERGE MERGE MERGE! IT'S FREE REAL ESTATE

**Comment by maxcell** [comment]
Omg @stevenpetryk chill

**Comment by stevenpetryk** [comment]
@maxcell JUST BEING AGGRESSIVELY ENCOURAGING, I LEARNED IT FROM A PARTICULAR COWORKER

**Comment by maxcell** [comment]
This looks good!

**Review by maxcell — APPROVED** [review]

**Pull request merged**
