### PR TITLE
Adds user creation endpoint

### PR DESCRIPTION
**Pull request by GregKWhite**
This PR adds a tiny User model, along with a UserController, housing a route for creating a new user. This endpoint is `POST /api/v1/users/new`.

### CODE REVIEW

**Comment by GregKWhite** [comment]
Oh! I should probably go ahead and add a Pawfile for this. @maxcell can you take a look at this PR sometime and let me know what you think?

**Comment by GregKWhite** [comment]
Okay! Pawfile is here! Ready for review when you have time @maxcell 👍

**Review by maxcell — CHANGES_REQUESTED** [review]
I loved the PR. I checked out all your tests 🍏 and even got PG running to play and successfully POST a new user.  I even checked to see for the 422. I love the JSON API for it as well. If you could update the README to include Paw information (import type) that would be ideal before it is all ready to :shipit: .

It is important to maintain a healthy Pawfile in order to include this inside of our final documentation of a fully detailed API spec (or at least of what we have so far).

**Review by maxcell — APPROVED** [review]
Great work 👍

**Comment by maxcell** [comment]
👍 Tested locally

**Pull request merged**
