### PR TITLE
Add fulltext search

### PR DESCRIPTION
**Pull request by GregKWhite**
Think it should be ready for review now. Yay

### CODE REVIEW

**Review by maxcell — COMMENTED** [review]
Do we only want to find streams for a user? Or do we want them to also be able to find other users?

**Comment by GregKWhite** [comment]
I'm not really sure what your asking here. Can you please clarify?

**Comment by maxcell** [comment]
To search for a user's name

**Comment by GregKWhite** [comment]
There's no searching for users going on here. This branch is only concerned with searching for streams by their title or description.

**Review by maxcell — APPROVED** [review]

**Pull request merged**
